name: 24-k8s-service
on:
  push:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gw-message-demo

jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v4
      - uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-secret:  ${{ secrets.SERVICE_ACCOUNT }}
          k8s-url: "https://49.13.23.0:6443"          
      - uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./Manifest/deployment.yaml
          namespace: 'trainer'
        
    